name             'fake'
maintainer       'Kannan Manickam'
maintainer_email 'me@arangamani.net'
license          'Apache 2.0'
description      'Installs/Configures on_failure'
version          '0.1.0'
