name             'meal'
maintainer       'Kannan Manickam'
maintainer_email 'me@arangamani.net'
license          'Apache 2.0'
description      'Used for eating meal for breakfast, lunch, dinner, etc.'
version          '0.1.0'
